name: Mis primeros pasos con Github Actions
on:
  push:
    branches:
      - main

jobs:
  hola-mundo:
    runs-on: ubuntu-22.04
    steps:
      - name: "Obtiene codigo"
      - uses: actions/checkout@v4

      - name: "Lista archivos"
        run: ls -lha
